name: ci
on: pull_request
jobs:
    test:
        runs-on: ubuntu-latest
        steps:
            - name: Cancel Running Workflows
              uses: styfle/cancel-workflow-action@0.6.0
              with:
                  access_token: ${{ github.token }}
            - name: Checkout repo
              uses: actions/checkout@v1
              with:
                  fetch-depth: 1
            - name: Set node version
              shell: bash -l {0}
              run: nvm install
            - name: Instal dependencies
              run: yarn install --frozen-lockfile
            - name: Run tests
              run: yarn test
