name: ci
on: pull_request
jobs:
    test:
        runs-on: ubuntu-latest
        steps:
            - name: Cancel running workflows
              uses: styfle/cancel-workflow-action@0.6.0
              with:
                  access_token: ${{ github.token }}
            - name: Checkout repo
              uses: actions/checkout@v1
              with:
                  fetch-depth: 1
            - name: Set node version
              shell: bash -l {0}
              run: nvm install
            - name: Cache node_modules
              uses: actions/cache@v2
              env:
                  cache-name: cache-node-modules
              with:
                  path: '**/node_modules'
                  key: dependencies-v1-${{ hashFiles('**/yarn.lock') }}
            - name: Instal dependencies
              if: steps.cache-node-modules.outputs.cache-hit != 'true'
              run: yarn install --frozen-lockfile
            - name: Run tests
              run: yarn test
